### ISSUE TITLE
安装过程中有一些异常，nginx 没有安装之类的试了很多次都这样  是安装脚本有问题吗？

### ISSUE THREAD

**Issue by tonghuanming** [mofeng-git/One-KVM#1]
root@onecloud:~/One-KVM# bash install.sh
Python 3.10.6
armv7l
update-alternatives: using /usr/bin/python3.10 to provide /usr/bin/python3 (python3) in auto mode
设备树文件覆盖成功！
32768+0 records in
32768+0 records out
16777216 bytes (17 MB, 16 MiB) copied, 1.11336 s, 15.1 MB/s
覆盖引导成功！
您似乎已经安装fruity-pikvm_0.2_armhf.deb，是否覆盖安装,此操作不会影响后续文件修改操作（Y/N）？
y
rm: cannot remove '/etc/kvmd/nginx/ssl/server.crt': No such file or directory
rm: cannot remove '/etc/kvmd/nginx/ssl/server.key': No such file or directory
正在安装PiKVM......
dpkg: regarding ./fruity-pikvm_0.2_armhf.deb containing fruity-pikvm, pre-dependency problem:
 fruity-pikvm pre-depends on nginx
  nginx is not installed.

dpkg: error processing archive ./fruity-pikvm_0.2_armhf.deb (--install):
 pre-dependency problem - not installing fruity-pikvm
Errors were encountered while processing:
 ./fruity-pikvm_0.2_armhf.deb
cp: cannot create regular file '/usr/share/kvmd/web/': No such file or directory
cp: cannot create regular file '/usr/local/lib/python3.10/kvmd-packages/': Not a directory
补丁应用成功！
GPIO-420脚本移动成功！
cp: cannot create regular file '/usr/local/lib/python3.10/kvmd-packages/kvmd/apps/kvmd/info/': No such file or directory
cp: cannot create regular file '/etc/kvmd/': Not a directory
install.sh: line 79: kvmd: command not found
内网访问地址为：
http://192.168.100.121
https://192.168.100.121
机器已执行重启命令，请手动给玩客云重新上电（拔插电源），然后就可以开始使用One-KVM了！

**Comment by tonghuanming** [comment]
安装完成后就进不去armbian系统了  是因为必须要插采集卡么？  我看hdmi输出 显示uboot卡在 启动emmc上

**Comment by mofeng-git** [comment]
感谢反馈，脚本逻辑存在问题已修复。您只需删除One-KVM目录下 installed.txt 重新执行install.sh即可。请按照提示在脚本执行完之后拔插电源（脚本执行完第一次需要硬重启，此后无影响）。
关于dtb，目前的dtb添加了cpu温度传感器但HDMI输出失效（后期我会尝试让两者共存），这就是画面停留在uboot启动emmc的原因。

**Comment by tonghuanming** [comment]
> 感谢反馈，脚本逻辑存在问题已修复。您只需删除One-KVM目录下 installed.txt 重新执行install.sh即可。请按照提示在脚本执行完之后拔插电源（脚本执行完第一次需要硬重启，此后无影响）。 关于dtb，目前的dtb添加了cpu温度传感器但HDMI输出失效（后期我会尝试让两者共存），这就是画面停留在uboot启动emmc的原因。

谢谢回复  还有就是经常获取不到IP 重启后就连不上了  这个是什么原因？ 因为手边没有串口线 也没办法看卡在哪里
