### ISSUE TITLE
[feature suggestion] 切换rootfs type为btrfs

### ISSUE THREAD

**Issue by Wikeolf** [mofeng-git/One-KVM#10]
btrfs的子卷特性可以将MSD在EMMC上的启用流程简化

**Comment by mofeng-git** [comment]
我感觉玩客云（可以视作嵌入式设备）的性能不太适合复杂高级的文件系统，后期会测试一下，如若收益大于开销的话再切换文件系统。感谢提议。

**Comment by mofeng-git** [comment]
精力有限，优先保证稳定性，放弃此计划。
