### ISSUE TITLE
画面条纹花屏 重启后正常过几十分钟又花屏

### ISSUE THREAD

**Issue by gavinwst** [mofeng-git/One-KVM#11]
![image](https://github.com/mofeng-git/One-KVM/assets/36542437/8fe22554-a45f-405b-8018-c181ab1775a7)
画面条纹花屏 重启后正常过几十分钟又花屏

**Comment by gavinwst** [comment]
kvmd-webterm@onecloud:~$ neofetch
                                 kvmd-webterm@onecloud 
                                 --------------------- 
      █ █ █ █ █ █ █ █ █ █ █      OS: Armbian (22.11.0-trunk) armv7l 
     ███████████████████████     Host: Xunlei OneCloud 
   ▄▄██                   ██▄▄   Kernel: 6.0.9-meson 
   ▄▄██    ███████████    ██▄▄   Uptime: 5 mins 
   ▄▄██   ██         ██   ██▄▄   Packages: 740 (dpkg) 
   ▄▄██   ██         ██   ██▄▄   Shell: nologin This account is currently not available. 
   ▄▄██   ██         ██   ██▄▄   Terminal: ttyd 
   ▄▄██   █████████████   ██▄▄   CPU: Amlogic Meson platform (4) @ 1.536GHz 
   ▄▄██   ██         ██   ██▄▄   Memory: 152MiB / 990MiB 
   ▄▄██   ██         ██   ██▄▄
   ▄▄██   ██         ██   ██▄▄                           
   ▄▄██                   ██▄▄                           
     ███████████████████████
      █ █ █ █ █ █ █ █ █ █ █

kvmd-webterm@onecloud:~$

**Comment by mofeng-git** [comment]
这是由于硬件（通常是HDMI采集卡松动，少数时候也可能是USB电流重启）原因引起的视频编解码错误。目前没有什么好办法，只能重置USB端口或重启玩客云。

**Comment by mofeng-git** [comment]
当然如果频繁发生的可以继续反馈。我这里遇到这种情况只有极少数。
