### ISSUE TITLE
有一个USB口不能用。

### ISSUE THREAD

**Issue by hy5528** [mofeng-git/One-KVM#12]
你好，我发现有一个USB口不能用。

**Comment by mofeng-git** [comment]
请问指的是One-KVM固件中的HDMI旁USB口无法外接U盘类的外接设备吗?
这是正常的，为了安装PikVM，我把这个USB口配置成了从设备模式（设备在Linux设备树中定义，/boot/dtb/meson8b-onecloud.dtb），不会显示的，只能通过usb gadget调用。

**Comment by hy5528** [comment]
谢谢！
