### ISSUE TITLE
如何打包一个类似 releases 页中的One-KVM-xxx.img 这样的预装了部分软件环境的直刷/线刷镜像？

### ISSUE THREAD

**Issue by ks4na** [mofeng-git/One-KVM#13]
我在玩客云 emmc 安装了 armbian ，然后装了一些软件。现在想要类似 One-KVM-xxx.img 这样做出一个开箱即用的镜像（以及线刷镜像），主要用于备份。

我尝试使用 releases 页提供的蓝蓝制作的 UBoot.eMMC.burn.img，然后参考 hzyitc 大佬的 `github action ci.yml` 中 build 步骤中的流程，尝试将一个U盘/Sd卡镜像 [Armbian-unofficial_24.5.0-trunk_Onecloud_bookworm_current_6.6.21.img.xz](https://github.com/hzyitc/armbian-onecloud/releases/download/ci-20240311-162146-UTC/Armbian-unofficial_24.5.0-trunk_Onecloud_bookworm_current_6.6.21.img.xz) 打包成线刷镜像 burn.img，然后线刷到玩客云运行起来了，整个打包线刷过程应该没有问题。

然后我尝试从当前玩客云环境打包一个普通U盘/Sd卡镜像, 参考的是 [制作机顶盒CM311-1a的armbian img文件](https://blog.csdn.net/ld_leon/article/details/125967415), 文章里面说是将 /boot 和 / 目录分别复制到 boot 和 rootfs 两个分区中，
但是我照着做出来的 img 镜像不管是直接通过 balenaEtcher 写入 U 盘后以U盘方式启动，还是打包成线刷镜像启动，都是有问题的，提示 `ALERT UUID... does not exist`，如下图所示：

![ALERT UUID 不存在](https://github.com/mofeng-git/One-KVM/assets/28475898/d0d9f6e9-1071-4907-a1b4-9c5f3c23fcbe)

我是新手，对于 uboot 和 armbian 打包不了解，查资料说可能与 `armbianEnv.txt` 的 `rootdev UUID` 有关，但是没找到资料说如何根据安装的设备 blkid 自动生成正确的 rootdev UUID，请教一下大佬这个问题该如何处理。

另外，不太确定如何从一个装好了软件的armbian系统生成一个开箱即用的镜像的步骤（dd 生成 armbian.img ，然后 fdisk 分区、losetup、mount , 最后将 /boot 和 / 目录分别复制到 boot 和 rootfs 两个分区中）是否正确，也希望大佬能够指导一下！

**Comment by mofeng-git** [comment]
简单说一下（有一些概念是我自创的，请勿介意），我目前打包先刷镜像的方式有两种：预编译，克隆重打包。

预编译适合安装流程简单软件（在chroot容器里面安装软件），代码透明度高，适用于开源软件系统镜像的构建。但仅仅是备份的话不推荐，因为整个构建流程过于复杂（uboot编译、内核编译、软件包构建、自定义软件安装）。即使有armbian/build的一件构建脚本学习成本也非常高。
此项目One-KVM就是预编译镜像，因为有完全100％源代码透明的需求 。

克隆重打包方式就是dd的升级版，可以现有安装好的系统重新打包为线刷镜像。原理是晶晨线刷镜像解包后是数个分区的普通dd的img镜像或压缩后的simg镜像。方法是用img2simg将boot分区和rootfs保存为boot.simg和rootfs.simg，在用amling工具解包普通线刷镜像，删除conmand.txt文件的验证行（即删除线刷分区校验），替换这两个分区的文件，最后用amlimg重新打包即可。
[玩客云OMV7 NAS固件](https://p1b237lu9xm.feishu.cn/docx/SL9HdzRUgoG4ntx8b1JcxeU2nsb)由于安装过于复杂使用此方式构建。

一些代码示例：[玩客云Linux系统（6.6.16内核）：Armbian、CentOS、ArchLinuxARM、DietPi](https://www.right.com.cn/forum/thread-8346314-1-1.html)

当然这只是思路，主要代码只有两条 img2simg和amlimg，如有疑问可以继续询问，我日后也计划出一篇完整的教程。

关于rootdev UUID，它定义了启动分区位置，是预先设置的。一个简单的处理办法是换为分区名称或分区位置，如rootdev=/dev/mmcblk0p2。直接替换uuid也是可以的，通过命令查看rootfs分区uuid直接替换rootdev=UUID=后面的字符串。

**Comment by mofeng-git** [comment]
> 另外，不太确定如何从一个装好了软件的armbian系统生成一个开箱即用的镜像的步骤（dd 生成 armbian.img ，然后 fdisk 分区、losetup、mount , 最后将 /boot 和 / 目录分别复制到 boot 和 rootfs 两个分区中）是否正确，也希望大佬能够指导一下！

关于这个方法有可行性，但需注意目的分区容量大小和复制过程中的文件权限问题。
如果能理解的话，接dd（生成img）或img2simg（生成simg），再直接替换分区的镜像文件，最后amling pack下可以使得整个流程更加简化。
