### ISSUE TITLE
MJPEG正常，H.264无法正常使用

### ISSUE THREAD

**Issue by upc-hao** [mofeng-git/One-KVM#15]
mofeng大佬，参考了你One-KVM维护记录中关于“Janus服务WebRTC/H.264功能”，跟着试了一下，结果h.264一直没有图像显示0fps dynamic，而切换mjpeg是完全正常的。
已经修改了janus里面的steamer文件内容，用“/usr/bin/janus --disable-colors --configs-folder=/etc/kvmd/janus_2”更改了配置路径
结果运行推流提示下面信息：
root@onecloud:~# ustreamer-dump --sink kvmd::ustreamer::jpeg --output - | ffmpeg -use_wallclock_as_timestamps 1 -i pipe: -c:v libx264 -pix_fmt yuv420p -preset:v ultrafast -tune:v zerolatency -an -filter:v fps=15 -f rtp rtp://127.0.0.1:5004
-- INFO  [3260.205          ] -- Using output: <stdout>
-- INFO  [3260.213          ] -- Using input-sink: kvmd::ustreamer::jpeg
**-- ERROR [3260.213          ] -- input-sink: Protocol version mismatch: sink=4, required=6**
-- INFO  [3260.213          ] -- Bye-bye
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers

**Comment by mofeng-git** [comment]
猜测原因同b站，使用了过于老旧的代码，新代码https://github.com/mofeng-git/One-KVM/blob/main/install.sh#L146。
可以使用的安装方法，git clone此项目，编辑install.sh尾部只保留kvmd-ffmpeg-h-26()函数模块，然后执行install.sh脚本。

**Comment by upc-hao** [comment]
对的就时这个原因，谢谢！用新的脚本重新安装了一下，重启后h.264正常工作了！
是刷的318的完整固件，之前没注意安装脚本注释掉了这一块，所以在跟着飞书文档的说明反复试也没成功。
