### ISSUE TITLE
SSH用户

### ISSUE THREAD

**Issue by FireSpell1** [mofeng-git/One-KVM#21]
One-KVM_Armbian SSH ROOT用户默认的密码是什么

**Comment by FireSpell1** [comment]
不需要了，原来是要接显示器和键盘自己改

**Comment by mofeng-git** [comment]
默认ssh账号密码为root/1234，ssh首次登陆后会提示修改密码。可以用不用实体显示器键盘的方式修改。

**Comment by FireSpell1** [comment]
嗯，我一开始是在pikvm的web终端操作的，那里是操作不了的，只能用自己的ssh客户端或是接显示器键盘

**Comment by FireSpell1** [comment]
pikvm终端用的那个kvmd开头的用户用root账号改了密码也不行，没办法sudo su或是sudo -i提升权限，应该是为了安全做了权限限制

**Comment by mofeng-git** [comment]
> pikvm终端用的那个kvmd开头的用户用root账号改了密码也不行，没办法sudo su或是sudo -i提升权限，应该是为了安全做了权限限制

对的，做了权限限制（不在sudoer用户组所以无法使用sudo命令）。如有需要，可以在网页终端使用su root命令切换至root账户，再执行需要特权的命令。

**Comment by FireSpell1** [comment]
好的，谢谢
