### ISSUE TITLE
x86安装不能成功

### ISSUE THREAD

**Issue by langma2020** [mofeng-git/One-KVM#23]
<img width="1192" alt="屏幕截图 2024-06-25 203905" src="https://github.com/mofeng-git/One-KVM/assets/67492806/06f45d5e-cfba-438e-b01c-8b8cc52f7e88">

**Comment by mofeng-git** [comment]
图中关键错误为"TypeError: alru cache()got an unexpected keyword argument 'ttl'"
非常抱歉，我在安装过程中无法复现此问题，你也没有提供相关日志（安装日志文件：/var/cache/kvmd/installer.log），所以我无法提供任何帮助。

**Comment by cmcpp** [comment]
遇到了这个一模一样的错误，请问 @mofeng-git 哪些操作系统，具体哪些版本通过了测试， 谢谢

**Comment by mofeng-git** [comment]
问题关闭，如仍需要推荐使用 Docker 版本。
