### ISSUE TITLE
[feature requested] 玩客云利用WIFI位GPIO作为RESET键

### ISSUE THREAD

**Issue by barryblueice** [mofeng-git/One-KVM#24]
gpioinfo查看gpiochip0内容：

![image](https://github.com/mofeng-git/One-KVM/assets/44601454/4ceac675-e381-4c8c-a35f-09b9d51e641e)

此处使用WIFI空焊位第12脚（GPIO11）作为RESET键GPIO，第一脚作为GND：

![image](https://github.com/mofeng-git/One-KVM/assets/44601454/7555be32-454a-4d56-afc2-0c12530704d7)

/usr/bin/onecloud_gpio.sh追加以下内容：

```bash
reset)
    gpioset -m time -s 1 gpiochip0 11=0
    gpioset gpiochip0 11=1
    ;;
```

/etc/kvmd/override.yaml对应处插入以下内容：

```bash
gpio:
    drivers:
        <原有内容...>
        reset_press:
            type: cmd
            cmd: [/usr/bin/sudo, onecloud_gpio.sh, reset]
    scheme:
        <原有内容...>
        reset_button:
            driver: reset_press
            pin: 0
            mode: output
            switch: false
    view:
        header:
            title: ATX
        table:
            <原有内容...>
            - ["#RESET重启:", reset_button|Press]
```

主板RESET键按照下图插入：

![image](https://github.com/mofeng-git/One-KVM/assets/44601454/c5824148-7f82-48de-8ee9-09d543333f5b)

即可实现RESET键。

***

根据目前已查到的datasheet内容（以rtl8189 sdio datasheet为例），如果使用第12脚作为RESET键GPIO，原有的WIFI模块应该不会受到影响（datasheet中WIFI模块对应为NC）：

![image](https://github.com/mofeng-git/One-KVM/assets/44601454/f5a3d95d-1192-4a1a-8b56-364b1a5ced5e)

其他脚位也可以，但是如果使用其他脚，对应datasheet查找后发现，可能会影响到后续wifi模块的加装（定义被使用了）。

参考的rtl8189 datasheet：[https://usermanual.wiki/Winplus/BT58189-5309787.pdf](https://usermanual.wiki/Winplus/BT58189-5309787.pdf)

**Comment by barryblueice** [comment]
在我的华南金牌X99-F8和K9-ETH试验后发现，GPIO脚要插入开机跳线7脚，GND脚需要插入9脚（普通RST开机跳线是57脚），如果插入57脚RST键将不会起作用；如果GPIO和GND插反了主板跑码FF，无法开机。

**Comment by mofeng-git** [comment]
好的，感谢你的测试。reset重启功能·已合并，对华南金牌X99-F8和K9-ETH这类特殊情况我将会在文档予以醒目提示。

**Comment by zcr268** [comment]
@barryblueice 焊接的位置可以再拍的清楚一点么

**Comment by barryblueice** [comment]
> @barryblueice 焊接的位置可以再拍的清楚一点么

给了脚位了自己慢慢数去

**Comment by zcr268** [comment]
![image](https://github.com/user-attachments/assets/f9024d55-1eee-4d15-94bb-29a4521f4b19)
实际使用的是上排最右触点和左排最上册.
另外我在j3455 上连接时发现电源键和重启键都有正反面,插反按键无效.
