### ISSUE TITLE
x86设备安装问题

### ISSUE THREAD

**Issue by Daydreamer97** [mofeng-git/One-KVM#26]
设备：
6 x Intel(R) Core(TM) i5-8600T CPU @ 2.30GHz 

环境：
运行在Linux 6.8.4-2-pve下的ubuntu-24.04 LTS（GNU/Linux 6.8.0-36-generic x86）

问题：
按教程安装完毕后，访问80端口，显示500 Internal Server Error。请教下需要怎么处理呢？

**Comment by mofeng-git** [comment]
也有其他用户反应了这个问题，似乎USB设备映射规则（udev rules）没有生效，目前需要手动配置设备路径。
500也说明kvmd服务没有启动成功（可执行命令systemctl status kvmd查看具体日志）。很可能是未找到kvmd-video、kvmd-hid设备，此情况下你需要在/etc/kvmd/目录下main.yaml和override.yaml配置文件中手动将/dev/kvmd-video、/dev/kvmd-hid修改为现在USB设备路径（可通过命令ls /dev/video*和ls /dev/ttyUSB*寻找，通常是/dev/video0和/dev/ttyUSB0）,修改后重启kvmd服务网页应该就能正常访问了。
