### ISSUE TITLE
网盘异常了

### ISSUE THREAD

**Issue by qingyuan0o0** [mofeng-git/One-KVM#27]
![image](https://github.com/mofeng-git/One-KVM/assets/18437931/2ff14138-ada8-4afc-84c4-e9393448ea43)

**Comment by mofeng-git** [comment]
感谢告知，已临时修复。
原因说明：网站迁移过程中出现了未预料的错误（且由于 DNS 解析问题当时未发现 PHP 版本oneinex nexmoe主题出问题了）。
