### ISSUE TITLE
双口玩客云上一个usb口不支持其它设备

### ISSUE THREAD

**Issue by Greedwolf** [mofeng-git/One-KVM#33]
在两个usb口上插了一个蓝牙，一个wifi，只有一个usb口能够识别设备，交换设备位置，另一个设备也能正常
root@onecloud:~# lsusb
Bus 002 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by mofeng-git** [comment]
整合包HDMI口旁USB默认配置为OTG device模式，无法主动识别设备只能被设备识别。有需要在系统脚本 /etc/rc.local 删除设置USB口为 device 模式的一行内容，然后重启系统,这样玩客云HDMI旁USB口才能正常使用。

**Comment by Greedwolf** [comment]
谢谢，已解决1

**Comment by Greedwolf** [comment]
谢谢，已解决
