### ISSUE TITLE
没办法修改ssh密码，到创建密码时候直接就断开连接

### ISSUE THREAD

**Issue by chibinyong** [mofeng-git/One-KVM#34]
Welcome to One-KVM_Armbian_by-SilentWind_for-Onecloud 24.8.0-trunk Jammy with Linux 6.6.34-current-meson

No end-user support: built from trunk

System load:   30%              Up time:       0 min    
Memory usage:  14% of 988M      IP:            192.168.31.168
CPU temp:      54°C             Usage of /:    22% of 6.9G      

[ 2 security updates available, 2 updates total: apt upgrade ]
Last check: 2024-09-28 14:32

[ Menu-driven system configuration (beta): sudo apt update && sudo apt install armbian-config ]

Last login: Tue Jun 18 07:28:28 2024

Waiting for system to finish booting ...
/usr/lib/armbian/armbian-firstlogin: line 471: /sys/class/graphics/fb0/virtual_size: No such file or directory
Welcome to One-KVM_Armbian_by-SilentWind_for-Onecloud! 

Documentation: https://docs.armbian.com/ | Community support: https://community.armbian.com/

IP address: 192.168.31.168

Create root password: 
连接断开

**Comment by chibinyong** [comment]
用的是 image 240318

**Comment by mofeng-git** [comment]
请使用ssh其他客户端（不包括finashell）完成ssh登录初始化，再使用finashell连接ssh。这是fianlshell软件的兼容性问题。

**Comment by chibinyong** [comment]
解决了 用网页自带的终端修改完后密码就可以用finalshell了
