### ISSUE TITLE
私家云2代，otg键盘无效

### ISSUE THREAD

**Issue by aircross** [mofeng-git/One-KVM#35]
log如下

`One-KVM OTG is enabled.
One-KVM video device is set to /dev/video1.
 USERNAME and PASSWORD environment variables is not set, using defalut(admin/admin).
Trying OTG Port...
rm: cannot remove '/run/kvmd/otg': No such file or directory
kvmd.apps.otg                       消息 --- 使用 UDC c9100000.usb
kvmd.apps.otg                       消息 --- 新建 gadget 'kvmd' ......
kvmd.apps.otg                       消息 --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/idVendor
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/idProduct
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/bcdUSB
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/bcdDevice
kvmd.apps.otg                       消息 --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/strings/0x409
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/strings/0x409/manufacturer
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/strings/0x409/product
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/strings/0x409/serialnumber
kvmd.apps.otg                       消息 --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/configs/c.1
kvmd.apps.otg                       消息 --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/configs/c.1/strings/0x409
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/configs/c.1/strings/0x409/configuration
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/configs/c.1/MaxPower
kvmd.apps.otg                       消息 --- MKDIR --- /run/kvmd/otg
kvmd.apps.otg                       消息 --- ===== HID-键盘 =====
kvmd.apps.otg                       消息 --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0
kvmd.apps.otg                       消息 --- WRITE --- [SKIPPED] /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/no_out_endpoint
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/protocol
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/subclass
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/report_length
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/report_desc
kvmd.apps.otg                       消息 --- SYMLINK - /sys/kernel/config/usb_gadget/kvmd/configs/c.1/hid.usb0 --> /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0
kvmd.apps.otg                       消息 --- WRITE --- /run/kvmd/otg/hid.usb0@meta.json
kvmd.apps.otg                       消息 --- ===== HID-鼠标 =====
kvmd.apps.otg                       消息 --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1
kvmd.apps.otg                       消息 --- WRITE --- [SKIPPED] /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/no_out_endpoint
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/protocol
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/subclass
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/report_length
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/report_desc
kvmd.apps.otg                       消息 --- SYMLINK - /sys/kernel/config/usb_gadget/kvmd/configs/c.1/hid.usb1 --> /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1
kvmd.apps.otg                       消息 --- WRITE --- /run/kvmd/otg/hid.usb1@meta.json
kvmd.apps.otg                       消息 --- ===== 准备完成 =====
kvmd.apps.otg                       消息 --- 启用此 gadget ......
kvmd.apps.otg                       消息 --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/UDC
kvmd.apps.otg                       消息 --- CHOWN --- kvmd - /sys/kernel/config/usb_gadget/kvmd/UDC
kvmd.apps.otg                       消息 --- CHOWN --- kvmd - /sys/kernel/config/usb_gadget/kvmd/configs/c.1
kvmd.apps.otg                       消息 --- 准备就绪`

**Comment by mofeng-git** [comment]
日志中没有看到相关错误，otg是正常运行的。正常运行时网页右上角键盘鼠标指示灯都会标绿。
![image](https://github.com/user-attachments/assets/e2cb3895-0ff7-4f11-ad9c-0f69d187d6df)

排查命令，获取更多信息：
`sudo docker logs kvmd | grep otg`
`sudo docker exec -it kvmd ls /dev`

**Comment by mofeng-git** [comment]
没有更新进展，将此 issue 关闭。
