### ISSUE TITLE
支持盒子吗？如华为悦盒ec6108v9c！

### ISSUE THREAD

**Issue by myseil** [mofeng-git/One-KVM#37]
如题，是否支持盒子？？
比如以下这些：[https://www.ecoo.top/devices](https://www.ecoo.top/devices)

**Comment by mofeng-git** [comment]
如果可以刷 Armbian 系统的话，理论上可以使用 docker 版，ch340+ch9329 和 USB HDMI 采集卡外设，此方案无需额外驱动兼容性非常强。

若盒子支持 Linux OTG 功能的话，还可以使用 OTG 模式支持更多拓展功能。

**Comment by myseil** [comment]
好的！  准备试试看！  感谢！
