### ISSUE TITLE
docker版One-KVM可以使用msd功能吗

### ISSUE THREAD

**Issue by huxuesen** [mofeng-git/One-KVM#38]
如题，昨天照着文档试了好几种方法，但是都显示驱动器offline，求大佬指点

**Comment by mofeng-git** [comment]
One-KVM 已经支持使用运行目录存放镜像，测试通过，明日发布。
此特性无需设置单独分区，仅需环境变量即可开启此功能。
![image](https://github.com/user-attachments/assets/8b641d7a-f575-4a96-9705-771187639d98)

**Comment by huxuesen** [comment]
牛，太帅了

**Comment by mofeng-git** [comment]
Docker 镜像已更新，OTG 模式 MSD 功能默认开启，可直接使用。
更新本地镜像并重建容器即可体验。
![image](https://github.com/user-attachments/assets/6b55d2fa-7925-4ff8-bf3d-846bcc5bc6bd)

**Comment by huxuesen** [comment]
ok，我这就测试一下

**Comment by huxuesen** [comment]
实测可用，感谢大佬
