### ISSUE TITLE
你好，安装了240318打包版本后会出现与玩客云连接的路由器没有网络。

### ISSUE THREAD

**Issue by hy5528** [mofeng-git/One-KVM#42]
安装了240318打包版本后会出现与玩客云连接的路由器没有网络，有时上级路由器都有影响，在多个路由器上测试过。

**Comment by mofeng-git** [comment]
你好，如果方便请您测试下最新版本（241014）是否也会出现此问题，判断这一个版本原因还是通病，便于缩小范围查找具体原因。

**Comment by hy5528** [comment]
我这查不到241018的？我的网络有问题？

**Comment by mofeng-git** [comment]
下载地址：
[Github](https://github.com/mofeng-git/One-KVM/releases/tag/v241004) 或者 [One-Index自建下载站](https://files.mofeng.run/1/OneKVM%20开箱即用固件)

**Comment by hy5528** [comment]
好的，有空试一下。

**Comment by hy5528** [comment]
谢谢你的回复。

**Comment by hy5528** [comment]
对了，我测试过image 240306的，这个没有问题。是不是与内核文件有关？

**Comment by hy5528** [comment]
h大建议用这个https://github.com/hzyitc/armbian-onecloud/files/11057794/fix-ethernet-uplink.zip，没人反馈。

**Comment by mofeng-git** [comment]
相关issue:https://github.com/hzyitc/armbian-onecloud/issues/2#issuecomment-1482142302

我这边无法复现问题没法测试，你可以试试反编译/boot/dtb/meson8b-onecloud.dtb修改对应内容并编译回去，看看是否还会干扰局域网。
示例命令：
```bash
dtc -I dtb -O dts /boot/dtb/meson8b-onecloud.dtb -o meson8b-onecloud.dts
nano meson8b-onecloud.dts
dtc -I dts -O dtb meson8b-onecloud.dts -o /boot/dtb/meson8b-onecloud.dtb
```
```
 	pinctrl-names = "default";
 
 	phy-handle = <&eth_phy>;
-	phy-mode = "rgmii-id";
+	phy-mode = "rgmii-rxid";
 
 	mdio {
 		compatible = "snps,dwmac-mdio";
```

在我的网络环境这个修改中似乎只影响网络速度，修改之后网络速度更快，所以在确认稳定性后这个更新下个整合包版本会合入。
![PixPin_2024-10-22_23-19-47](https://github.com/user-attachments/assets/de43f5e5-8e24-4d1c-a4b1-d3a928de7469)

**Comment by hy5528** [comment]
因为我玩客云实在太渣，只有5.9内核能正常启动，测试完你的所有5.9内核版本。都有断网现象，不定时发生。严重的时候玩客云开机后全屋断网。5.9以上的容易死机，其他人版本也一样。能不能发个linux-image-current-meson5.9文件的上来测试一下，看是不是与这个有关。

**Comment by hy5528** [comment]
原来240306的版本也出现了断网。其它的人的从5.88升到5.9的版本没出现断网。

**Comment by mofeng-git** [comment]
> 因为我玩客云实在太渣，只有5.9内核能正常启动，测试完你的所有5.9内核版本。都有断网现象，不定时发生。严重的时候玩客云开机后全屋断网。5.9以上的容易死机，其他人版本也一样。能不能发个linux-image-current-meson5.9文件的上来测试一下，看是不是与这个有关。

https://github.com/mofeng-git/One-KVM/releases/download/v0.56/linux-image-current-aml-s812_24.03_armhf.deb
这个，其他的没法帮助你了

**Comment by mofeng-git** [comment]
长时间没有更进一步信息，此问题将被关闭。
