### ISSUE TITLE
可以考虑添加录制被控电脑视频的功能吗

### ISSUE THREAD

**Issue by Logan147** [mofeng-git/One-KVM#44]
很多用户可能会像我一样遇到录制被控电脑画面的需求，比如打游戏之类的，可以考虑添加一下录制视频的功能吗，就像直接对采集卡画面录制那样，并保存为mp4

**Comment by Logan147** [comment]
我按照pikvm的官方文档中录制视频的部分尝试了一下发现录制出来的是花屏qaq

**Comment by Logan147** [comment]
onekvm文档中的开启h264功能的脚本消失了 kvmd_h264_install.sh

**Comment by Logan147** [comment]
![image](https://github.com/user-attachments/assets/12817345-fbe3-4f13-bf18-cbb3609d797a)

**Comment by Logan147** [comment]
web端的h264也是花屏
![image](https://github.com/user-attachments/assets/78a775a6-217e-415a-bb04-b05d5abab38f)

**Comment by Logan147** [comment]
web端的mjpg可以正常使用，但是用pikvm文档中的ffmpeg方式录屏，录制出来的视频就和h264web端一样的花屏
![image](https://github.com/user-attachments/assets/439a1734-eb7f-4ce0-a367-515c85385b7e)

**Comment by Logan147** [comment]
![image](https://github.com/user-attachments/assets/913ee11c-2aa9-4416-9127-362fc34fb62c)

**Comment by Logan147** [comment]
![image](https://github.com/user-attachments/assets/0cd1631b-4196-41c9-a84a-85b57bdb52d9)

**Comment by Logan147** [comment]
这些文档和网上教程中用到的bash脚本都没有了!!!

**Comment by Logan147** [comment]
额，终于找到了，在这个tag下有
![image](https://github.com/user-attachments/assets/91235e98-0d94-442b-904b-51354ed4832b)

**Comment by Logan147** [comment]
额不要用docker版本的kvmd，因为kvm_h264_install.sh里用到了systemctl命令，docker里无法执行会报错，导致无法支持h264，还是直接用install.sh在实体机上安装吧

**Comment by Logan147** [comment]
额也报错了
![image](https://github.com/user-attachments/assets/c6fa6f65-b4ed-4f8c-8193-965ebc0aa981)

**Comment by Logan147** [comment]
![image](https://github.com/user-attachments/assets/6a70779b-794b-433d-9c7e-2980434ab006)
web端的帧率还是可以的，就是没有录屏功能很难受

**Comment by Logan147** [comment]
发现这个命令可以在docker里录制，但是录制出来的视频无法直接播放因为不是h264格式，并且还没有音频流，就是没声，作者会考虑添加一下录制功能吗，我看pikvm项目里也有人反映过让pikvm作者添加录制功能，但是该作者直接放弃了，让用户凑合用，希望作者可以认真考虑一下这个严肃的问题，最后添加一下录制功能，直接录制出h264编码的有声音的mp4文件，好吧
ustreamer-dump --sink kvmd::ustreamer::jpeg --output - | ffmpeg -use_wallclock_as_timestamps 1 -i pipe: -c:v copy test.mp4

**Comment by Logan147** [comment]
![image](https://github.com/user-attachments/assets/cf122c9a-fb14-4a37-bc21-705b8ab9da5c)

**Comment by Logan147** [comment]
![image](https://github.com/user-attachments/assets/eb96da00-b520-45a3-b551-da9c99be67c8)
我上面的命令录制出来的视频经过小丸工具箱转换压缩为h264后可以播放了，但是没声，，这个录制视频功能现在真的很鸡肋，极其需要再次编写

**Comment by Logan147** [comment]
这是onekvm的web页面，可以看到是无法选择声音的，没有声音输出
![image](https://github.com/user-attachments/assets/1876ed45-e61f-4a5d-b2fe-6e516839410a)
这是pikvm官方文档中的声音部分，可以看到是可以在web端选择的
![image](https://github.com/user-attachments/assets/1b34a566-f52b-4fd5-bfa7-c3d59ca68c49)

**Comment by Logan147** [comment]
onekvm 不是说docker中的ustreamer是修改过的用了libx264技术可以支持h264的吗，那onekvm的web页面中的h264方式怎么还是花屏啊。。。

**Comment by mofeng-git** [comment]
> onekvm 不是说docker中的ustreamer是修改过的用了libx264技术可以支持h264的吗，那onekvm的web页面中的h264方式怎么还是花屏啊。。。

多刷新几次网页看看，我测试 docker 版 h.264 功能是正常可用的。
![image](https://github.com/user-attachments/assets/c14668f5-9cf6-4c3f-9dcc-f54fa5d3640d)

**Comment by mofeng-git** [comment]
关于视频录制：
当前思路是在网页添加视频录制按钮，由网页前端（浏览器）进行录制当前视频画面的录制，会尝试做一个demo出来。
因为后端录制视频性能占用非常大且难以控制时序，非常不可靠。

关于音频：
音频需要后端支持（pikvm官方的是特定声卡驱动，对于USB采集卡无法使用需要部分重写），我对音视频 C语言 开发很陌生加之由于此前没有相关需求没有编写。目前已添加到开发计划中，

**Comment by mofeng-git** [comment]
视频录制已实现
![PixPin_2024-11-04_21-29-54](https://github.com/user-attachments/assets/a3300137-3d5a-4535-88bf-3e43b05b6136)

**Comment by mofeng-git** [comment]
音频支持已初步完成，不久后更新
![image](https://github.com/user-attachments/assets/b57689be-6e2e-4cef-982c-25f53481ce3d)

**Comment by Logan147** [comment]
好的，多谢作者帮忙解答，我再试试，视频录制功能和音频支持以后会添加到docker版本中吗？我现在用的是radxa zero开发板，只能用docker版本的onekvm

**Comment by Logan147** [comment]
多谢作者更新文档支持🤗
