### ISSUE TITLE
玩客云最新的烧录镜像无法进行软关机或者重启，使用sudo reboot命令重启会失联

### ISSUE THREAD

**Issue by Stary1st** [mofeng-git/One-KVM#48]
如题，我的机器在运行几小时后也会失联，原因不明。用ssh命令进行重启会直接失联。

**Comment by mofeng-git** [comment]
我这里无法复现。
如果你需要帮助请更进一步请提供如下信息：
1. 软重启失联频率，100%发生还是概率发生？
2. 软重启后指示灯颜色变化，以及玩客云自身HDMI显示画面变化详细信息？
3. 玩客云版本，刷机包版本（名称）。

**Comment by Stary1st** [comment]
问题已解决，经测试是刷写镜像不规范，导致出现随机错误，在USB Burn tool里面选择force erase all烧录后使用正常

**Comment by pengkaiwei** [comment]
我的好像插了usb直通到被控设备后。ssh 重启就不正常，会一直红灯。拔掉usb直通模拟鼠标线就好了。
双头usb已经去掉红色电源正极乐。 有可能插上usb模拟鼠标线，会进烧录模式？

我烧录的时候没有勾选bootloader，我有我重新烧录测试一下，谢谢！

**Comment by mofeng-git** [comment]
> 我的好像插了usb直通到被控设备后。ssh 重启就不正常，会一直红灯。拔掉usb直通模拟鼠标线就好了。
> 双头usb已经去掉红色电源正极乐。 有可能插上usb模拟鼠标线，会进烧录模式？
> 
> 我烧录的时候没有勾选bootloader，我有我重新烧录测试一下，谢谢！



这个问题的原因是使用了旧版bootloader，量连接刷机线是自动进入了刷机模式而不是Armbian系统，勾选bootloader烧录即可。
