### ISSUE TITLE
pip3 install -U Pillow速度过慢，下载超时导致安装不成功，建议修改源

### ISSUE THREAD

**Issue by ZirrorDmage** [mofeng-git/One-KVM#5]
脚本整体安装过程非常流畅，实践效果很好，就是首次安装时pillow下载速度只有几十kb，结果下载超时自动跳入后续流程
可以考虑安装前新增换源操作`pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple/`，极大加快下载速度，避免安装失败

**Comment by mofeng-git** [comment]
感谢提议·，已添加换源命令
