### ISSUE TITLE
是否支持贝壳云P1？

### ISSUE THREAD

**Issue by le45tx1m** [mofeng-git/One-KVM#51]
看配置贝壳云和我家云基本一致，同是 RK3328，RAM 1G，ROM 8G，有4个USB 3.0，很好解决了我家云USB不够的问题，不知道能不能用我家云的包直接刷呢？

![1732719148957](https://github.com/user-attachments/assets/373406bf-d059-463b-8817-8edd8e5c1fe4)

**Comment by mofeng-git** [comment]
> 看配置贝壳云和我家云基本一致，同是 RK3328，RAM 1G，ROM 8G，有4个USB 3.0，很好解决了我家云USB不够的问题，不知道能不能用我家云的包直接刷呢？

 不能，两者差异设备树dtb非常大并不通用。
你可以为贝壳云刷入合适的Linux系统再使用docker部署One-KVM，docker安装One-KVM是一个非常轻松且通用的办法。

**Comment by le45tx1m** [comment]
感谢回复，那我先拿我家云凑合着，主要想上USB3.0接MS2130，现在用玩客云接MS2109，1080p下帧率开高一点画面会有色块有点难受
