### ISSUE TITLE
希望未来能支持矿渣 2345 章鱼星球

### ISSUE THREAD

**Issue by le45tx1m** [mofeng-git/One-KVM#52]
本项目目前扩展支持了许多设备，希望有机会能把和玩客云同为矿渣的章鱼星球救一下%……
s912，2G RAM，8G ROM，USB x2，SD x1

**Comment by le45tx1m** [comment]
不好意思刚看到下面有赞助链接 XD ，赞助 88 聊表支持
![QQ截图20241127231022](https://github.com/user-attachments/assets/fa83e5e6-3927-4ea8-b119-b248a60d6686)

**Comment by mofeng-git** [comment]
好的，近期安排。由于近期计划较多，可能不会太快，预计两周后放出整合包镜像和相关文档。

**Comment by mofeng-git** [comment]
章鱼星球整合包已经制作初测完成。
镜像链接：https://github.com/mofeng-git/One-KVM/releases/download/v241204/One-KVM_by-SilentWind_Octopus-Flanet_241204.img.xz
使用文档：https://one-kvm.mofeng.run/octopus-flanet_install/

**Comment by le45tx1m** [comment]
感谢，这么快就出成品了。等周末我试试，有问题会回馈改进🙏🏻
