### ISSUE TITLE
能否增加电视盒子用的固件。

### ISSUE THREAD

**Issue by test19850** [mofeng-git/One-KVM#54]
手中有创维E900和中兴ZXV10 B860A机顶盒，希望出此硬件的固件，万分感谢。

**Comment by mofeng-git** [comment]
我这里没有这两个硬件，暂无计划购买。
若有需要可为你远程打包镜像，发给我你机顶盒使用基础Armbian镜像，打包One-KVM后发回给你，由你自行测试。

**Comment by mofeng-git** [comment]
基础Armbian镜像就是你机器实测能正常运行的镜像，我会以这个镜像为基础在里面添加One-KVM的文件和依赖。

举例：现在我在适配章鱼星球，我到https://github.com/ophub/amlogic-s9xxx-armbian/下载了Armbian_24.11.0_amlogic_s912_bookworm_6.1.114_server_2024.11.01.img ，测试发现镜像能正常运行主要功能也正常，那这个文件就是用来我打包One-KVM整合包的基础镜像。

**Comment by test19850** [comment]
刚刚拆了一个创维的盒子，cpu是Hi3798.我找找相应的镜像。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mofeng-git/One-KVM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月1日(星期天) 晚上10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mofeng-git/One-KVM] 能否增加电视盒子用的固件。 (Issue #54)





 
基础Armbian镜像就是你机器实测能正常运行的镜像，我会以这个镜像为基础在里面添加One-KVM的文件和依赖。
 
举例：现在我在适配章鱼星球，我到https://github.com/ophub/amlogic-s9xxx-armbian/下载了Armbian_24.11.0_amlogic_s912_bookworm_6.1.114_server_2024.11.01.img ，测试发现镜像能正常运行主要功能也正常，那这个文件就是用来我打包One-KVM整合包的基础镜像。

**Comment by mofeng-git** [comment]
无进一步回复，关闭问题。

**Comment by jamyu-li** [comment]
中兴ZXV10 B860A机顶盒参考这里：
[https://github.com/jamyu-li/Armbian-on-B860A-S812-TVBOX](url)
