### ISSUE TITLE
进入windows的bios界面时条纹屏，无法显示正常画面

### ISSUE THREAD

**Issue by houbowen123** [mofeng-git/One-KVM#55]
进入windows的bios界面时条纹屏，无法显示正常画面。 不知道有什么好的解决办法吗？

**Comment by mofeng-git** [comment]
请给一张无法显示画面条纹截图，当前信息不足无法判断原因。

当然你可以尝试一些通过的办法：开启bios csm，调整采集卡分辨率。

**Comment by mofeng-git** [comment]
笔记本通常不支持在外置显示器上显示bios界面。
