### ISSUE TITLE
修改了msd存储位置后上传就会出现500报错

### ISSUE THREAD

**Issue by wuweiyaowwy** [mofeng-git/One-KVM#56]
![Uploading Snipaste_2024-12-10_20-31-10.png…]()

**Comment by mofeng-git** [comment]
方便的话请提供更多信息以便复现和解决问题：
整合包还是都docker部署，何种硬件;
msd路径修改方式（编辑源代码还是修改配置文件还是修改目录映射）；
错误日志（systemctl status kvmd 或 docker logs kvmd）;
