### ISSUE TITLE
玩客云接一控多KVM无效

### ISSUE THREAD

**Issue by Pr-wing** [mofeng-git/One-KVM#57]
设备: 玩客云
KVM: https://item.taobao.com/item.htm?id=734220456188

1. 画面输出功能在onekvm上测试可以正常切换输出和显示
2. 设备控制功能, KVM接在台式电脑上测试可以正常工作

KVM输出端接到玩客云后无法控制设备, 右上角键盘鼠标图标绿色, 被控端之一linux有"usb 1 4 device descriptor read 64 error 71"的输出.
![QQ20241214-112359](https://github.com/user-attachments/assets/3d9aa24f-1217-4345-a8d5-a9f34dd24b56)
![default](https://github.com/user-attachments/assets/34d93c0b-3c4c-475f-a5cb-bfdcd4cdf020)
![QQ20241214-112449](https://github.com/user-attachments/assets/7779d5c1-40bc-49a5-99b7-353d5875cf8b)

**Comment by mofeng-git** [comment]
默认开启MSD 功能，MSD 功能与 KVM 切换器支持冲突使用时只能二选一。
图中错误通过在/etc/kvmd/override.yaml配置文件禁用msd功能可以解决。

**Comment by Pr-wing** [comment]
> 默认开启MSD 功能，MSD 功能与 KVM 切换器支持冲突使用时只能二选一。 图中错误通过在/etc/kvmd/override.yaml配置文件禁用msd功能可以解决。

已解决, 多谢:)
