### ISSUE TITLE
建议固件支持无线网卡usb驱动

### ISSUE THREAD

**Issue by ghost** [mofeng-git/One-KVM#59]

**Comment by mofeng-git** [comment]
这个需求暂时无计划实现，原因如下：
1. 我没有测试设备，无法验证功能是否正常运作
2. 我是用的是基础包+预装软件的方式构建整合包，部分基础包我没有对应Linux源代码，且依次从源码构建系统非常繁琐

**Comment by mmdjiji** [comment]
其实直接把有线网口替换插一个网桥/5G模块就好了，解耦合有利于降低成本和增加可靠性，而且玩客云只支持俩USB，采集卡占一个OTG占一个根本没有机会再插无线网卡
