### ISSUE TITLE
HID 離線問題

### ISSUE THREAD

**Issue by sillydanny** [mofeng-git/One-KVM#61]
### 問題：
> 用玩客雲(純刷版)、我家雲(Docker)都可以正常啟用One-KVM，除了首次可以使用Keyboard，後就一直是HID離線。

### 嘗試解決：
1. 查看USB裝置連線，可正常連接到採集卡和CH9329控制線
2. 重新啟動ONE-KVM主機、重新連接被控制機器
3. 重新啟用Docker 容器

### 結果：
> 依家未能解決HID 離線問題。

![HID-Offline_2024-12-20_105007](https://github.com/user-attachments/assets/04499fb8-ba08-4f5e-bd4d-6b9e769d3b27)

**Comment by mofeng-git** [comment]
当前无法判断具体原因，需要更多日志才能分析，可以执行如下命令
docker logs kvmd

**Comment by sillydanny** [comment]
> 當前無法判斷具體原因，需要更多日誌才能分析，可以執行如下命令 docker logs kvmd

這是日誌內容：
> kvmd  | kvmd.plugins.hid.ch9329          ERROR --- Invalid chip response: ChipResponseError: Too short response, HID might be disconnected

![2024-12-23_131627](https://github.com/user-attachments/assets/73e8e753-b8be-400d-b63f-5c9508053349)

**Comment by YoshiokaHikari** [comment]
请问怎么解决这个问题，我也遇到了
