### ISSUE TITLE
image240221默认端口和密码怎么修改？

### ISSUE THREAD

**Issue by abe520** [mofeng-git/One-KVM#8]
1.编辑/etc/kvmd/nginx/下80端口后,执行systemctl restart kvmd kvmd-nginx后，还是默认80端口
2.kvmd-htpasswd del admin删除admin用户后，无法通过新建用户登录vnc（没找到vnc端口配置文件）
3.linux-dtb-edge和linux-headers和linux-image-edge是做什么用的？
4.内置emmc分区MSD，还能不能使用tf扩展空间？

**Comment by yyystephen** [comment]
同样遇到这个问题，请问解决了么？
2.kvmd-htpasswd del admin删除admin用户后，无法通过新建用户登录vnc（没找到vnc端口配置文件）
